install gcc via homebrew
to try to fix a conan incompatibility with MacOS' default gcc
installation:

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
$ conan install . --build=missing

Auto detecting your dev setup to initialize the default profile (/Users/travis/.conan/profiles/default)

CC and CXX: gcc, g++

ERROR: gcc detected as a frontend using apple-clang. Compiler not supported

ERROR: Unable to find a working compiler
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~